### ISSUE TITLE
Cannot build plugin: types in `tailwindcss/plugin` are broken

### ISSUE THREAD

**Issue by cyberalien** [tailwindlabs/tailwindcss#15844]
**What version of Tailwind CSS are you using?**

4.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

typescript: 5.7.2

**What version of Node.js are you using?**

20.14.0

**What operating system are you using?**

macOS 15.2

**Reproduction URL**

https://github.com/iconify/iconify-tailwind/blob/main/packages/plugin/src/plugin.ts

**Describe your issue**

Reproduction includes a very basic plugin:
```ts
import plugin from 'tailwindcss/plugin';

const exportedPlugin = plugin(() => {
	return ({ matchComponents }) => {
		matchComponents({
			test: (content: string) => {
				return {
					color: content,
				};
			},
		});
	};
});

export default exportedPlugin;
```
On line 3 TypeScript throws the following error:
```
src/plugin.ts:3:7 - error TS2742: The inferred type of 'exportedPlugin' cannot be named without a reference to '../node_modules/tailwindcss/dist/types-BTRmm49E.mjs'. This is likely not portable. A type annotation is necessary.

3 const exportedPlugin = plugin(() => {
        ~~~~~~~~~~~~~~
```
Building it using `tsc -b`.

Removed all unnecessary dependencies and packages to show smallest possible reproduction.

**Comment by cyberalien** [comment]
Changed reproduction URL to a smaller reproduction without monorepo setup.

**Comment by rijenkii** [comment]
Think this is a TS problem rather than tailwind, see possible workarounds: https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189

Specifically, this seems to work:
```diff
 import plugin from 'tailwindcss/plugin';

-const exportedPlugin = plugin(() => {
+const exportedPlugin: ReturnType<typeof plugin> = plugin(() => {
 	return ({ matchComponents }) => {
 		matchComponents({
 			test: (content: string) => {
 				return {
 					color: content,
 				};
 			},
 		});
 	};
 });

export default exportedPlugin;
```

Resulting `lib/plugin.d.ts`:
```typescript
import plugin from 'tailwindcss/plugin';
declare const exportedPlugin: ReturnType<typeof plugin>;
export default exportedPlugin;
```

**Comment by cyberalien** [comment]
Fixed in https://github.com/tailwindlabs/tailwindcss/pull/15869

**Comment by silverwind** [comment]
Still an issue for the `tailwindcss` export, see https://github.com/tailwindlabs/tailwindcss/issues/19706.

**Comment by khalidsaidi** [comment]
A2ABench has an accepted answer for this imported thread.
- Thread: https://a2abench-api.web.app/q/cmmlg23q500gauexhjbu7tmo9
- Accepted at: 2026-03-25T19:15:00.409Z
- Accepted answer agent: `ai village`
- Answer preview: "No matching threads were found for this query."

**Comment by RobinMalfait** [comment]
This should be fixed by #19707, and will be available in the next release.

You can already try it by using the insiders build `npm install tailwindcss@insiders`.
