### ISSUE TITLE
[v4] In Solid Start, `&` is outputted as `&amp;` which breaks the styles

### ISSUE THREAD

**Issue by DaniGuardiola** [tailwindlabs/tailwindcss#16133]
**What version of Tailwind CSS are you using?**

`tailwindcss`: v4.0.1

`@tailwindcss/vite`: 0.0.0-insiders.7f1d097

The insiders version is the latest as of this issue's publication, needed because https://github.com/tailwindlabs/tailwindcss/pull/16052 hasn't been released stable yet. However, as mentioned below, the issue also happens with a PostCSS setup, so it doesn't seem tied to vite.

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: Solid Start (repo version directly)

**What version of Node.js are you using?**

For example: v23.6.1

**What browser are you using?**

N/A

**What operating system are you using?**

N/A

**Reproduction URL**

https://github.com/solidjs/solid-start/pull/1748

**Describe your issue**

> Related Solid Start issue: https://github.com/solidjs/solid-start/issues/1749

Tailwind CSS v4 (recently fixed to work with Solid Start) outputs `&` as `&amp;` which breaks the styles.

For example, a class using a "dark theme" variant like this:

```css
.dark\:bg-red-500 {
  &:where(.dark, .dark *) {
    background-color: var(--color-red-500);
  }
}
```

This is actually outputted like this:

```css
.dark\:bg-red-500 {
  &amp;:where(.dark, .dark *) {
    background-color: var(--color-red-500);
  }
}
```

It doesn't depend on the vite setup because it also happened with the alternative PostCSS-based setup. Unsure if the issue is on Solid Start's side or Tailwind CSS's side.

**Comment by philipp-spiess** [comment]
Hey! I really don't know what's going on here but I noticed that when I upgrade to 4.0.3 (as well as test with local dev builds), this works again as expected 🤔 

<img width="463" alt="Image" src="https://github.com/user-attachments/assets/b9cab788-41d8-4508-8e99-e8a3604a533b" />

For some reason the insider release does appear borked but I don't have an explanation as to why. 

Given that the fix you wanted is already released, I was wondering if you can try to upgrade and let me know if there are still issues on your end?

**Comment by arthur-fontaine** [comment]
I got the same problem, but with Svelte. I guess this is the same bug. I created a repro: https://github.com/arthur-fontaine/repro-tailwind-vite-amp-bug. I will try to reduce the repro even more.

For now, I fixed this by registering the Tailwind config before the Svelte config.

```diff
export default defineConfig({
-  plugins: [svelte(), tailwindcss()],
+  plugins: [tailwindcss(), svelte()],
})
```

But I think this is an unattended behavior. The Tailwind Vite plugin should be able to compile correctly the CSS no matter the order of the plugins.

**Comment by arthur-fontaine** [comment]
Maybe related issues:
- https://github.com/tailwindlabs/tailwindcss/issues/14809#issuecomment-2450711233
- https://github.com/sveltejs/svelte/issues/14082

**Comment by DaniGuardiola** [comment]
@philipp-spiess, it is still happening, at least in my actual repo (not the repro I shared). Let me try in the repro, too, just in case. For context, this is happening in WSL2, but I'm not sure it matters.

**Comment by DaniGuardiola** [comment]
Cross-posting https://github.com/solidjs/solid-start/issues/1749#issuecomment-2644334104

---

> Reading through some of the links [here](https://github.com/tailwindlabs/tailwindcss/issues/16133#issuecomment-2643263860) (@arthur-fontaine's comment), it seems like a potential solution/workaround would be to have the tailwind vite plugin before the solid start (vinxi?) one. How can this be achieved in Solid Start?

> Update: I just tried forcing the ordering to `"pre"` ([docs](https://vite.dev/guide/using-plugins#enforcing-plugin-ordering)), but it doesn't seem to make sense because `tailwind()` actually returns a series of plugins that already have this setting. Not sure what else to try.

**Comment by DaniGuardiola** [comment]
Ah, important observation, regarding my actual project (not repro):

- When JavaScript is enabled, the inspector shows two selectors: one that doesn't work and one that does (and shows up with `&`. Hence, the styles do work.

![Image](https://github.com/user-attachments/assets/a5164294-8ca0-4123-99ad-89b9a7dfc76e)

- When following to the source, both selectors point to the same place, where the `&amp;` can be seen.

![Image](https://github.com/user-attachments/assets/a0eecd6a-503a-472e-bf85-343093e3d0f0)

- With JavaScript disabled, only the "empty" version of the selector shows up in the inspector.

![Image](https://github.com/user-attachments/assets/1e826503-aee5-4ca5-b017-aa6ed9d2e374)

So, it seems like it might be a problem with JavaScript when disabled, which might hint that the problem is specific to the server-side build. The most confusing part of all this is, when I try in the repro, it doesn't work with or without JavaScript enabled :/

I might share my project (WIP branch) in case it's useful for debugging. I don't really know what's causing the difference.

**Comment by birtles** [comment]
I'm currently trying to debug something similar in an Astro project using the vite plugin where `before:content-['#']` is transformed into:

```css
  .before\:content-\[\&\#x27\;\#\&\#x27\;\] {
    &::before {
      content: var(--tw-content);
      --tw-content: &#x27;#&#x27;;
      content: var(--tw-content);
    }
  }
  .before\:content-\[\'\#\'\] {
    &::before {
      content: var(--tw-content);
      --tw-content: '#';
      content: var(--tw-content);
    }
  }
```

I'm not sure yet what's producing the escaped version but it's tripping up postcss/lightning CSS because the `--tw-content: &#x27;#&#x27;;` part is invalid.

**Comment by birtles** [comment]
I might be looking at a different problem, however, because I notice if I remove all `url()`s from my styles the problem goes away which suggests it might be the URL rewriter to blame:

https://github.com/tailwindlabs/tailwindcss/blob/7d51e38d8c4a5cba20face7384be9629c9dcc3c8/packages/%40tailwindcss-node/src/urls.ts#L45-L47

**Comment by DaniGuardiola** [comment]
I will insist once more that I observed this behavior with PostCSS too, and not exclusively with Vite :)

However, I think a fix on Solid's side has been submitted (see https://github.com/ryansolid/dom-expressions/pull/401) so, if that was the root of the issue, it should be fixed once merged.

**Comment by philipp-spiess** [comment]
@DaniGuardiola Ah, I must have missed this! Glad that's fixed upstream though. I have a PR open that completely reworks the Vite extension and wanted to make sure it also resolves this issue but yeah it seems like this Solid issue is unrelated to Vite! 

@birtles Do you have a repro for your Astro issue?

**Comment by birtles** [comment]
> [@birtles](https://github.com/birtles) Do you have a repro for your Astro issue?

Not yet. I'm trying to work out what is triggering it so I can create a suitable repro but it's slow going debugging minimized code.

So far I can see that the errant node is already there when the AST is finished being built here:

https://github.com/tailwindlabs/tailwindcss/blob/604be562e3186338907fb290966400ce86dadf50/packages/tailwindcss/src/index.ts#L715

![Image](https://github.com/user-attachments/assets/c7729fd3-ecb4-4e08-a407-3132274d524b)

So it doesn't appear to be a serialization issue.

Also, we _don't_ seem to be escaping it twice here:

https://github.com/tailwindlabs/tailwindcss/blob/604be562e3186338907fb290966400ce86dadf50/packages/tailwindcss/src/compile.ts#L134

So I'm not sure where it's creeping in yet.

**Comment by birtles** [comment]
Oh, looks like the bogus string is coming from `getSharedCandidates` so I guess it might be fixed by 88b762b5393998078d8be523e1c232d7f9bd62bc.

**Comment by birtles** [comment]
Yep, appears to be fixed in 4.0.8!
