### ISSUE TITLE
Error: Cannot find module '../lightningcss.linux-x64-musl.node'

### ISSUE THREAD

**Issue by therealsras** [tailwindlabs/tailwindcss#17958]
<img width="489" alt="Image" src="https://github.com/user-attachments/assets/56b469cf-00f4-4235-b8e0-8a17090c2dec" />
I had workaround working. but I see it will solve this but no.

```
#37 3.296 > next build
#37 3.296
#37 4.772    ▲ Next.js 15.3.1
#37 4.773    - Environments: .env.production
#37 4.840    Creating an optimized production build ...
#37 59.97 Failed to compile.
#37 59.97
#37 59.98 app/layout.tsx
#37 59.98 An error occurred in `next/font`.
#37 59.98
#37 59.98 Error: Cannot find module '../lightningcss.linux-x64-musl.node'
#37 59.98 Require stack:
#37 59.98 - /app/node_modules/lightningcss/node/index.js
#37 59.98 - /app/node_modules/@tailwindcss/node/dist/index.js
#37 59.98 - /app/node_modules/@tailwindcss/postcss/dist/index.js
#37 59.98 - /app/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
#37 59.98 - /app/node_modules/next/dist/build/webpack/config/blocks/css/index.js
#37 59.98 - /app/node_modules/next/dist/build/webpack/config/index.js
#37 59.98 - /app/node_modules/next/dist/build/webpack-config.js
#37 59.98 - /app/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js
#37 59.98 - /app/node_modules/next/dist/build/collect-build-traces.js
#37 59.98 - /app/node_modules/next/dist/build/index.js
#37 59.98 - /app/node_modules/next/dist/cli/next-build.js
#37 59.98     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
#37 59.98     at /app/node_modules/next/dist/server/require-hook.js:55:36
#37 59.98     at Module._load (node:internal/modules/cjs/loader:981:27)
#37 59.98     at Module.require (node:internal/modules/cjs/loader:1231:19)
#37 59.98     at mod.require (/app/node_modules/next/dist/server/require-hook.js:65:28)
#37 59.98     at require (node:internal/modules/helpers:177:18)
#37 59.98     at Object.<anonymous> (/app/node_modules/lightningcss/node/index.js:22:22)
#37 59.98     at Module._compile (node:internal/modules/cjs/loader:1364:14)
#37 59.98     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
#37 59.98     at Module.load (node:internal/modules/cjs/loader:1203:32)
#37 59.98
#37 59.98 lib/fonts.ts
#37 59.98 An error occurred in `next/font`.
#37 59.98
#37 59.98 Error: Cannot find module '../lightningcss.linux-x64-musl.node'
#37 59.98 Require stack:
#37 59.98 - /app/node_modules/lightningcss/node/index.js
#37 59.98 - /app/node_modules/@tailwindcss/node/dist/index.js
#37 59.98 - /app/node_modules/@tailwindcss/postcss/dist/index.js
#37 59.98 - /app/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
#37 59.98 - /app/node_modules/next/dist/build/webpack/config/blocks/css/index.js
#37 59.98 - /app/node_modules/next/dist/build/webpack/config/index.js
#37 59.98 - /app/node_modules/next/dist/build/webpack-config.js
#37 59.98 - /app/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js
#37 59.98 - /app/node_modules/next/dist/build/collect-build-traces.js
#37 59.98 - /app/node_modules/next/dist/build/index.js
#37 59.98 - /app/node_modules/next/dist/cli/next-build.js
#37 59.98     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
#37 59.98     at /app/node_modules/next/dist/server/require-hook.js:55:36
#37 59.98     at Module._load (node:internal/modules/cjs/loader:981:27)
#37 59.98     at Module.require (node:internal/modules/cjs/loader:1231:19)
#37 59.98     at mod.require (/app/node_modules/next/dist/server/require-hook.js:65:28)
#37 59.98     at require (node:internal/modules/helpers:177:18)
#37 59.98     at Object.<anonymous> (/app/node_modules/lightningcss/node/index.js:22:22)
#37 59.98     at Module._compile (node:internal/modules/cjs/loader:1364:14)
#37 59.98     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
#37 59.98     at Module.load (node:internal/modules/cjs/loader:1203:32)
#37 59.98
#37 59.98
#37 59.98 > Build failed because of webpack errors
#37 60.14 npm notice
#37 60.14 npm notice New major version of npm available! 10.8.2 -> 11.3.0
#37 60.14 npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.3.0
#37 60.14 npm notice To update run: npm install -g npm@11.3.0
#37 60.14 npm notice
#37 ERROR: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1

------
> [web-app-dev builder 5/5] RUN npm run build:
59.98     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
59.98     at Module.load (node:internal/modules/cjs/loader:1203:32)
59.98
59.98
59.98 > Build failed because of webpack errors
60.14 npm notice
60.14 npm notice New major version of npm available! 10.8.2 -> 11.3.0
60.14 npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.3.0
60.14 npm notice To update run: npm install -g npm@11.3.0
60.14 npm notice
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
Error ❌ failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```
**What version of Tailwind CSS are you using?**

For example: v4.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: Next.js 15.3.1

**What version of Node.js are you using?**
dockerfile: node:18-alpine

For example: Chrome, Safari, or N/A
Ubuntu Docker

**Comment by therealsras** [comment]
#15806

**Comment by philipp-spiess** [comment]
Hey! Yeah this is expected, we can only fix this for our native extension but your bundler still has issues it seems. In the thread #15806 some folks have had issues with only our binary so we still went ahead with this fix. 

I suggest you add the necessary dependency for `lightningcss.linux-x64-musl.node` manually or update npm to the latest version, see: https://github.com/tailwindlabs/tailwindcss/issues/15806#issuecomment-2853991957

**Comment by philipp-spiess** [comment]
Can you clarify what you mean by:

>  I had workaround working.

**Comment by therealsras** [comment]
@philipp-spiess are you saying to upgrade npm version in dockerfile. I can build successfully on Mac Arm. but docker could not 


sample from dockerfile

FROM node:18-alpine AS deps

**Comment by therealsras** [comment]
> Hey! Yeah this is expected, we can only fix this for our native extension but your bundler still has issues it seems. In the thread [#15806](https://github.com/tailwindlabs/tailwindcss/issues/15806) some folks have had issues with only our binary so we still went ahead with this fix.
> 
> I suggest you add the necessary dependency for `lightningcss.linux-x64-musl.node` manually or update npm to the latest version, see: [#15806 (comment)](https://github.com/tailwindlabs/tailwindcss/issues/15806#issuecomment-2853991957)

are you meaning to keep the optionalDependencies as it was.

**Comment by therealsras** [comment]
> oxide

okay.  upgrade node version won't fix this right?

and what 4.1.6 fixed is we can remove ones **oxide** not **lightningcss**, and will it also be fixed?

**Comment by philipp-spiess** [comment]
> okay. upgrade node version won't fix this right?

You will need the latest npm version, I don't know if it will work with older node versions. See https://github.com/npm/cli/releases/tag/v11.3.0

> and what 4.1.6 fixed is we can remove ones **oxide** not **lightningcss**, and will it also be fixed?

Yeah, Oxide is the library we maintain, Lightningcss is a third-party library so it is not as easy to apply the fix. We might have to add something in the future but ideally this can be fixed upstream. I want to wait first and see if our fix has helped at least somewhat.

Are you able to get it working by adding back only this part?

<img width="493" alt="Image" src="https://github.com/user-attachments/assets/cf19ec31-46ac-4428-8964-bef144bdd608" />

**Comment by therealsras** [comment]
@philipp-spiess if trying lastest npm it will causes problem
```

#33 [web-app-dev deps 3/6] RUN npm install -g npm@latest
#33 2.860 npm error code EBADENGINE
#33 2.861 npm error engine Unsupported engine
#33 2.861 npm error engine Not compatible with your version of node/npm: npm@11.3.0
#33 2.861 npm error notsup Not compatible with your version of node/npm: npm@11.3.0
#33 2.861 npm error notsup Required: {"node":"^20.17.0 || >=22.9.0"}
#33 2.861 npm error notsup Actual:   {"npm":"10.8.2","node":"v18.20.8"}
#33 2.862 npm error A complete log of this run can be found in: /root/.npm/_logs/2025-05-09T14_54_01_686Z-debug-0.log
#33 ERROR: process "/bin/sh -c npm install -g npm@latest" did not complete successfully: exit code: 1
```

**Comment by philipp-spiess** [comment]
@thatguychrisw yeah seems like it doesn't work with Node 18 anymore. Maybe you can try using `node 20` and see if that works? Would be awesome to get confirmation that the npm bugfix actually resolves this issue!

**Comment by therealsras** [comment]
> [@thatguychrisw](https://github.com/thatguychrisw) yeah seems like it doesn't work with Node 18 anymore. Maybe you can try using `node 20` and see if that works? Would be awesome to get confirmation that the npm bugfix actually resolves this issue!

yes, right node 20 can build successfully. just there are some warning as below.
```

#38 DONE 0.1s
#39 [web-app-dev deps 6/6] RUN npm install --omit-dev
#39 0.667 npm warn Unknown cli config "--omit-dev". This will stop working in the next major version of npm.
#39 7.304 npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
#39 7.803 npm warn deprecated npmlog@5.0.1: This package is no longer supported.
#39 9.339 npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
#39 9.919 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#39 10.03 npm warn deprecated gauge@3.0.2: This package is no longer supported.
#39 13.67 npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
```

**Comment by ghostlexly** [comment]
Same problem on Macbook M1, on "node:22.17.0-bullseye-slim":

Error: Cannot find module '../lightningcss.linux-arm64-gnu.node'

**Comment by kfayelun** [comment]
This happened to me just now when upgrading npm from `10.9.0` to `11.5.2`. 
Node version `22.12.0`, tailwind `4.1.11`, for 2 different vite apps in the same monorepo.

I recon some wouldn't want to downgrade npm, but after downgrading again everything works as before.

**Comment by shaqaruden** [comment]
I just started a new project today using a custom docker compose stack and I am seeing this error. I ensured that npm/node are using the latest images. I checked the npm version and I am seeing 11.6.0

<img width="687" height="648" alt="Image" src="https://github.com/user-attachments/assets/da8a98d9-4ac6-45df-ac52-51d195e06c68" />

**Comment by fejx** [comment]
This has already been written above but just to clarify: This command should fix the issue for now:
```
npm install lightningcss-linux-arm64-musl lightningcss-linux-x64-gnu lightningcss-linux-x64-musl --save-optional
```

**Comment by Anhnguyenanh123** [comment]
### 

> This has already been written above but just to clarify: This command should fix the issue for now:
> 
> ```
> npm install lightningcss-linux-arm64-musl lightningcss-linux-x64-gnu lightningcss-linux-x64-musl --save-optional
> ```

can you help me explain few days ago, i followed your instructions and it built successfully but now i can not build it anymore

<img width="605" height="525" alt="Image" src="https://github.com/user-attachments/assets/a398d43a-bfbc-4a01-b9ad-fcb96f4ea181" />
<img width="1225" height="748" alt="Image" src="https://github.com/user-attachments/assets/6b80fa9b-864b-4235-bd04-525bd9cec3ff" />

**Comment by kobago** [comment]
I also had this problem, but it went away after installing the version released four days ago.

**Comment by ebulku** [comment]
having the same issue after update to 4.2.1

**Comment by rayyan808** [comment]
Reporting issue still exists on 4.2.1

**Comment by khalidsaidi** [comment]
A2ABench has an accepted answer for this imported thread.
- Thread: https://a2abench-api.web.app/q/cmmlg23ot00g3uexhrjz5094h
- Accepted at: 2026-03-25T19:14:57.432Z
- Accepted answer agent: `ai village`
- Answer preview: "No matching threads were found for this query."

**Comment by lumio** [comment]
> I had workaround working. but I see it will solve this but no.

@therealsras I'm running into the same issue right now. What did you do as a workaround? Currently nothing I found online currently solves this issue.

**Comment by therealsras** [comment]
> > okay. upgrade node version won't fix this right?
> 
> You will need the latest npm version, I don't know if it will work with older node versions. See https://github.com/npm/cli/releases/tag/v11.3.0
> 
> > and what 4.1.6 fixed is we can remove ones **oxide** not **lightningcss**, and will it also be fixed?
> 
> Yeah, Oxide is the library we maintain, Lightningcss is a third-party library so it is not as easy to apply the fix. We might have to add something in the future but ideally this can be fixed upstream. I want to wait first and see if our fix has helped at least somewhat.
> 
> Are you able to get it working by adding back only this part?
> 
> <img alt="Image" width="493" src="https://private-user-images.githubusercontent.com/458591/442183328-cf19ec31-46ac-4428-8964-bef144bdd608.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzUwOTgwNjUsIm5iZiI6MTc3NTA5Nzc2NSwicGF0aCI6Ii80NTg1OTEvNDQyMTgzMzI4LWNmMTllYzMxLTQ2YWMtNDQyOC04OTY0LWJlZjE0NGJkZDYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQwMlQwMjQyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTc2MWI5ZGIwZDEyNGZhNjk3MjdmOWRiZGU5MjI5OTRkZDhmMmM3MmM4ZTg1NjU3N2Q3ZDg5YmNhMDVkNzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vkVBvcmxgru7Rs0rMQtqGLxMDokFUBHkkHHiYUhMsYM">

@lumio , this was my workaround, not sure if it works for your

**Comment by lumio** [comment]
@therealsras ah thanks. Skimmed over the comments too quickly and overlooked that comment. Currently I fixed it by manually linking the right binary on build which is way too hacky for me

**Comment by lumio** [comment]
Ok. I struggled with this the last 2 days or so. My suspicion right now is that the latest Docker Desktop for macOS is the issue. I downgraded from 4.67 to 4.58.1 and it works again. It looks like Docker somehow did not properly propagate the architecture of the container (although this is just an assumption!)

I was so frustrated with this that I created a fresh Next.js project using pnpm this time. Once I dockerized it I had the same issues with v4.67

**// edit: looks like v4.67 alone is the issue. Downgrading to v4.66.1 fixed the issue for me**

**Comment by sydneyvaughn75-ops** [comment]
Thanks for the updates. Confirming the issue still exists on 4.2.1.

**Comment by takashi-kurino** [comment]
I wasted two days. I've stopped using automatic Docker updates. Thank you.

**Comment by sydneyvaughn75-ops** [comment]
Sorry to hear that.

**Comment by donxp** [comment]
Issue seems fixed on Docker 4.68

**Comment by denizkoele** [comment]
i upgraded from 4.14.0 to 4.82.0 and it didnt worked


> This has already been written above but just to clarify: This command should fix the issue for now:
> 
> ```
> npm install lightningcss-linux-arm64-musl lightningcss-linux-x64-gnu lightningcss-linux-x64-musl --save-optional
> ```


installing these and deleting package-lock.json did
